# Generated by Django 2.2.7 on 2021-12-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist2patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Xabar turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('datetime', models.DateTimeField(verbose_name="Xabar jo'natilgan vaqt")),
                ('is_read', models.BooleanField(verbose_name="O'qilganmi?")),
            ],
            options={
                'verbose_name': 'D2P Xabar',
                'verbose_name_plural': 'D2P Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Patient2dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Xabar turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('datetime', models.DateTimeField(verbose_name="Xabar jo'natilgan vaqt")),
                ('is_read', models.BooleanField(verbose_name="O'qilganmi?")),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_recipient', to='dentist.User', verbose_name='Tish shifokori')),
            ],
            options={
                'verbose_name': 'P2D Xabar',
                'verbose_name_plural': 'P2D Xabarlar',
            },
        ),
    ]
