# Generated by Django 2.2.7 on 2021-12-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('patient', '0001_initial'),
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient2dentist',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sender', to='patient.User', verbose_name='Bemor'),
        ),
        migrations.AddField(
            model_name='dentist2patient',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_recipient', to='patient.User', verbose_name='Bemor'),
        ),
        migrations.AddField(
            model_name='dentist2patient',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_sender', to='dentist.User', verbose_name='Tish shifokori'),
        ),
    ]
