# Generated by Django 3.2.5 on 2022-05-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20220107_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('datetime', models.DateTimeField(verbose_name="Xabar jo'natilgan vaqt")),
                ('is_read', models.BooleanField(verbose_name="O'qilganmi?")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
