# Generated by Django 3.2.5 on 2022-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Xabar jo'natilgan vaqt"),
        ),
    ]
