# Generated by Django 3.2.5 on 2022-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist2patient',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Xabar jo'natilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Xabar jo'natilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='patient2dentist',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Xabar jo'natilgan vaqt"),
        ),
    ]
