# Generated by Django 2.2.7 on 2021-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('uidb64', models.CharField(max_length=100, verbose_name='uidb64')),
                ('token', models.CharField(max_length=150, verbose_name='Token')),
                ('is_active', models.BooleanField(verbose_name='Faolligi')),
            ],
            options={
                'verbose_name': 'Parol tiklanishi',
                'verbose_name_plural': 'Parol tiklanishlari',
            },
        ),
    ]
