# Generated by Django 2.2.7 on 2021-12-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentist', '__first__'),
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Sabab')),
                ('comment', models.TextField(verbose_name='Izohlar')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.User', verbose_name='Tish shifokori')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.User', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': "So'rov",
                'verbose_name_plural': "So'rovlar",
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(default=None, verbose_name='Boshlanish vaqti')),
                ('end', models.DateTimeField(default=None, verbose_name='Tugash vaqti')),
                ('comment', models.TextField(null=True, verbose_name='Izohlar')),
                ('status', models.CharField(max_length=50, verbose_name='Qabul holati')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.User', verbose_name='Tish shifokori')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.User', verbose_name='Bemor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.Service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabullar',
            },
        ),
    ]
