# Generated by Django 3.2.5 on 2022-03-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0006_auto_20220323_1121'),
        ('appointment', '0002_auto_20220107_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_appointment', to='dentist.user', verbose_name='Tish shifokori'),
        ),
    ]
