# Generated by Django 3.2.5 on 2022-06-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_illness_fainting'),
        ('dentist', '0011_auto_20220419_0000'),
        ('appointment', '0003_alter_appointment_dentist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Bajarilgan')),
                ('comment', models.TextField(null=True, verbose_name='Izohlar')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_procedure', to='appointment.appointment', verbose_name='Qabul')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_service', to='dentist.service', verbose_name='Xizmat')),
                ('tooth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_tooth', to='patient.tooth', verbose_name='Tish')),
            ],
            options={
                'verbose_name': 'Tish holati',
                'verbose_name_plural': 'Tish holatlari',
            },
        ),
    ]
