# Generated by Django 2.2.7 on 2021-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'OITS',
            },
        ),
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Spirtli ichimlik ichasizmi?',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Allergiya',
            },
        ),
        migrations.CreateModel(
            name='Anesthesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Narkoz',
            },
        ),
        migrations.CreateModel(
            name='Asthma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Bronxial astma',
            },
        ),
        migrations.CreateModel(
            name='Blood_disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Qon kasali',
            },
        ),
        migrations.CreateModel(
            name='Diabet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Qandli diabet',
            },
        ),
        migrations.CreateModel(
            name='Dizziness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Bosh aylanishi',
            },
        ),
        migrations.CreateModel(
            name='Epilepsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Epilepsiya',
            },
        ),
        migrations.CreateModel(
            name='Heart_attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Yurak xurujiga uchraganmisiz?',
            },
        ),
        migrations.CreateModel(
            name='Hepatitis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Gepatit B',
            },
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Doimiy dorilar',
            },
        ),
        migrations.CreateModel(
            name='Oncologic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Onkologik kasalliklar',
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Homiladorlik',
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Qon bosimi',
            },
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Insultga uchraganmisiz?',
            },
        ),
        migrations.CreateModel(
            name='Tuberculosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Sil kasalligi',
            },
        ),
    ]
