# Generated by Django 3.2.5 on 2022-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aids',
            options={'verbose_name': 'OITS', 'verbose_name_plural': 'OITS'},
        ),
        migrations.AlterModelOptions(
            name='alcohol',
            options={'verbose_name': 'Spirtli ichimlik ichasizmi?', 'verbose_name_plural': 'Spirtli ichimlik ichasizmi?'},
        ),
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Allergiya', 'verbose_name_plural': 'Allergiya'},
        ),
        migrations.AlterModelOptions(
            name='anesthesia',
            options={'verbose_name': 'Narkoz', 'verbose_name_plural': 'Narkoz'},
        ),
        migrations.AlterModelOptions(
            name='asthma',
            options={'verbose_name': 'Bronxial astma', 'verbose_name_plural': 'Bronxial astma'},
        ),
        migrations.AlterModelOptions(
            name='blood_disease',
            options={'verbose_name': 'Qon kasali', 'verbose_name_plural': 'Qon kasali'},
        ),
        migrations.AlterModelOptions(
            name='diabet',
            options={'verbose_name': 'Qandli diabet', 'verbose_name_plural': 'Qandli diabet'},
        ),
        migrations.AlterModelOptions(
            name='dizziness',
            options={'verbose_name': 'Bosh aylanishi', 'verbose_name_plural': 'Bosh aylanishi'},
        ),
        migrations.AlterModelOptions(
            name='epilepsy',
            options={'verbose_name': 'Epilepsiya', 'verbose_name_plural': 'Epilepsiya'},
        ),
        migrations.AlterModelOptions(
            name='heart_attack',
            options={'verbose_name': 'Yurak xurujiga uchraganmisiz?', 'verbose_name_plural': 'Yurak xurujiga uchraganmisiz?'},
        ),
        migrations.AlterModelOptions(
            name='hepatitis',
            options={'verbose_name': 'Gepatit B', 'verbose_name_plural': 'Gepatit B'},
        ),
        migrations.AlterModelOptions(
            name='medications',
            options={'verbose_name': 'Doimiy dorilar', 'verbose_name_plural': 'Doimiy dorilar'},
        ),
        migrations.AlterModelOptions(
            name='oncologic',
            options={'verbose_name': 'Onkologik kasalliklar', 'verbose_name_plural': 'Onkologik kasalliklar'},
        ),
        migrations.AlterModelOptions(
            name='pregnancy',
            options={'verbose_name': 'Homiladorlik', 'verbose_name_plural': 'Homiladorlik'},
        ),
        migrations.AlterModelOptions(
            name='pressure',
            options={'verbose_name': 'Qon bosimi', 'verbose_name_plural': 'Qon bosimi'},
        ),
        migrations.AlterModelOptions(
            name='stroke',
            options={'verbose_name': 'Insultga uchraganmisiz?', 'verbose_name_plural': 'Insultga uchraganmisiz?'},
        ),
        migrations.AlterModelOptions(
            name='tuberculosis',
            options={'verbose_name': 'Sil kasalligi', 'verbose_name_plural': 'Sil kasalligi'},
        ),
        migrations.AlterField(
            model_name='aids',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='anesthesia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asthma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blood_disease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diabet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dizziness',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='epilepsy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='heart_attack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hepatitis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oncologic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
