# Generated by Django 3.2.5 on 2022-04-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0002_auto_20220107_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('lastname', models.CharField(max_length=255, verbose_name='Ism')),
                ('tg_user_id', models.CharField(max_length=25, verbose_name='Telegram ID')),
                ('status', models.CharField(default='mainmenu', max_length=100, verbose_name='Status (qaysi sahifadaligi)')),
                ('current_page', models.IntegerField(default=0, verbose_name='Nechinchi sahifada')),
                ('latitude', models.FloatField(default=0, verbose_name='Kenglik')),
                ('longitude', models.FloatField(default=0, verbose_name='Uzunlik')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language_tg_user', to='baseapp.language', verbose_name='Til')),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchisi',
                'verbose_name_plural': 'Telegram foydalanuvchilari',
            },
        ),
    ]
