# Generated by Django 2.2.7 on 2021-12-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_region', to='baseapp.Region', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Shifoxona',
                'verbose_name_plural': 'Shifoxonalar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xizmat nomi')),
                ('duration', models.IntegerField(verbose_name='Xizmat davomiyligi')),
                ('price', models.IntegerField(verbose_name='Xizmat narxi')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Telefon raqami')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('image', models.ImageField(default='dentists/photos/default.png', upload_to='dentists/photos/', verbose_name='Rasmi')),
                ('experience', models.IntegerField(verbose_name='Tajriba')),
                ('worktime_begin', models.TimeField(verbose_name='Ish vaqti boshlanishi')),
                ('worktime_end', models.TimeField(verbose_name='Ish vaqti tugashi')),
                ('is_fullday', models.BooleanField(verbose_name='24 soat rejimi')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_clinic', to='dentist.Clinic', verbose_name='Shifoxona')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_gender', to='baseapp.Gender', verbose_name='Jins')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_language', to='baseapp.Language', verbose_name='Tili')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_user', to=settings.AUTH_USER_MODEL, verbose_name='Tish shifokori')),
            ],
            options={
                'verbose_name': 'Tish shifokori',
                'verbose_name_plural': 'Tish shifokorlari',
            },
        ),
        migrations.CreateModel(
            name='User_translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='MyDentist dagi FIShi')),
                ('speciality', models.CharField(max_length=500, verbose_name='Soha')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_user_translation', to='dentist.User', verbose_name='Tish shifokori')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_language_translation', to='baseapp.Language', verbose_name='Tili')),
            ],
            options={
                'verbose_name': "Tish shifokorining ma'lumoti",
                'verbose_name_plural': "Tish shifokorining ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Service_translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xizmat nomi')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_language_translation', to='baseapp.Language', verbose_name='Tili')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_service_translation', to='dentist.Service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': "Xizmatning ma'lumoti",
                'verbose_name_plural': "Xizmatning ma'lumotlari",
            },
        ),
        migrations.AddField(
            model_name='service',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.User', verbose_name='Tish shifokori'),
        ),
        migrations.CreateModel(
            name='Clinic_translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('orientir', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mo'ljal")),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_clinic_translation', to='dentist.Clinic', verbose_name='Shifoxona')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_language', to='baseapp.Language', verbose_name='Til')),
            ],
            options={
                'verbose_name': "Shifoxonaning ma'lumoti",
                'verbose_name_plural': "Shifoxonaning ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Cabinet_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dentists/cabinet_photos/', verbose_name='Rasm')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.User', verbose_name='Tish shifokori')),
            ],
            options={
                'verbose_name': 'Kabinet rasmi',
                'verbose_name_plural': 'Kabinet rasmlari',
            },
        ),
    ]
