# Generated by Django 3.2.5 on 2022-02-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20220107_1418'),
        ('dentist', '0002_auto_20220107_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sabab nomi')),
                ('value', models.IntegerField(verbose_name='Raqami')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.language', verbose_name='Tili')),
            ],
            options={
                'verbose_name': 'Sabab ',
                'verbose_name_plural': 'Sabablar',
            },
        ),
    ]
