# Generated by Django 3.2.5 on 2022-03-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_key_patient'),
        ('dentist', '0003_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_patient', to='dentist.user', verbose_name='Tish shifokori')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_patient', to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Tish shifokorining bemori ',
                'verbose_name_plural': 'Tish shifokorining bemorlari',
            },
        ),
    ]
