# Generated by Django 3.2.5 on 2022-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_days',
            field=models.IntegerField(default=7, verbose_name='Ish kunlari soni (6 yoki 7)'),
            preserve_default=False,
        ),
    ]
