# Generated by Django 3.2.5 on 2022-03-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0005_user_work_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_service', to='dentist.user', verbose_name='Tish shifokori'),
        ),
        migrations.CreateModel(
            name='Expire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Tugash muddati')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_expire', to='dentist.user', verbose_name='Aktivlangan')),
            ],
            options={
                'verbose_name': 'Shifokor aktivligi ',
                'verbose_name_plural': 'Shifokor aktivliglari',
            },
        ),
    ]
