# Generated by Django 3.2.5 on 2022-04-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0007_auto_20220405_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Animatsiya nomi')),
                ('file', models.FileField(upload_to='animations/', verbose_name='Fayl')),
            ],
        ),
    ]
