# Generated by Django 3.2.5 on 2022-04-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20220107_1418'),
        ('dentist', '0008_animation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animation',
            options={'verbose_name': 'Animatsiya ', 'verbose_name_plural': 'Animatsiyalar'},
        ),
        migrations.CreateModel(
            name='Animation_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Animatsiya nomi')),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animation_translation', to='dentist.animation', verbose_name='Animatsiya')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animation_language', to='baseapp.language', verbose_name='Til')),
            ],
            options={
                'verbose_name': "Animatsiya ma'lumoti ",
                'verbose_name_plural': "Animatsiya ma'lumotlari",
            },
        ),
    ]
