# Generated by Django 3.2.5 on 2022-04-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20220107_1418'),
        ('dentist', '0009_auto_20220409_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Xizmat turining nomi')),
            ],
            options={
                'verbose_name': 'Xizmat turi',
                'verbose_name_plural': 'Xizmat turlari',
            },
        ),
        migrations.CreateModel(
            name='Service_category_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Xizmat turining nomi')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category_language_translation', to='baseapp.language', verbose_name='Tili')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category_translation', to='dentist.service_category', verbose_name='Xizmat turi')),
            ],
            options={
                'verbose_name': "Xizmat turi ma'lumoti",
                'verbose_name_plural': "Xizmat turi ma'lumotlari",
            },
        ),
    ]
