# Generated by Django 3.2.5 on 2022-04-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0010_service_category_service_category_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_category_service', to='dentist.service_category', verbose_name='Xizmat turi'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_queued',
            field=models.BooleanField(default=False, verbose_name='Navbatsiz'),
        ),
    ]
