# Generated by Django 3.2.5 on 2022-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0011_auto_20220419_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name="Nomini o'zgartirish mumkinmi?"),
        ),
    ]
