# Generated by Django 3.2.5 on 2022-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0012_service_is_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Xizmat narxi'),
        ),
    ]
