# Generated by Django 3.2.5 on 2022-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0013_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Xizmat davomiyligi'),
        ),
    ]
