# Generated by Django 3.2.5 on 2022-06-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0014_alter_service_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
    ]
