# Generated by Django 3.2.5 on 2022-07-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0015_remove_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='one_tooth',
            field=models.BooleanField(default=False, verbose_name='Bitta tish uchun'),
        ),
    ]
