# Generated by Django 2.2.7 on 2021-12-16 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('illness', '0001_initial'),
        ('baseapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooth_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Holat nomi')),
                ('prefix', models.CharField(max_length=50, verbose_name="Holat qo'shimchasi")),
            ],
            options={
                'verbose_name': 'Tish holati',
                'verbose_name_plural': 'Tish holatlari',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('image', models.ImageField(upload_to='patients/photos/', verbose_name='Rasmi')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_gender', to='baseapp.Gender', verbose_name='Jins')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_language', to='baseapp.Language', verbose_name='Tili')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL, verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Tish raqami')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tooth', to='patient.User', verbose_name='Bemor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tooth_status', to='patient.Tooth_status', verbose_name='Tish holati')),
            ],
            options={
                'verbose_name': 'Tish',
                'verbose_name_plural': 'Tishlar',
            },
        ),
        migrations.CreateModel(
            name='Process_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patients/process_photos/', verbose_name='Ish jarayonidagi rasm')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_process_photo', to='patient.User', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Tish holati',
                'verbose_name_plural': 'Tish holatlari',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ish nomi')),
                ('is_done', models.BooleanField(verbose_name='Qilinganligi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_plan', to='patient.User', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Qilingan ish',
                'verbose_name_plural': 'Qilingan ishlar',
            },
        ),
        migrations.CreateModel(
            name='Other_Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Alcohol', verbose_name='Spirtli ichimlik ichasizmi?')),
                ('blood_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Blood_disease', verbose_name='Qon kasali')),
                ('epilepsy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Epilepsy', verbose_name='Epilepsiya')),
                ('heart_attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Heart_attack', verbose_name='Yurak xurujiga uchraganmisiz?')),
                ('medications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Medications', verbose_name='Doimiy dorilar')),
                ('oncologic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Oncologic', verbose_name='Onkologik kasalliklar')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.User', verbose_name='Bemor')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Pregnancy', verbose_name='Homiladorlik')),
                ('stroke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Stroke', verbose_name='Insultga uchraganmisiz?')),
                ('tuberculosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Tuberculosis', verbose_name='Sil kasalligi')),
            ],
            options={
                'verbose_name': 'Bemor kasalligi',
                'verbose_name_plural': 'Bemor kasalliklari',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.AIDS', verbose_name='OITS')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Allergy', verbose_name='Allergiya')),
                ('anesthesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Anesthesia', verbose_name='Narkoz')),
                ('asthma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Asthma', verbose_name='Bronxial astma')),
                ('diabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Diabet', verbose_name='Qandli diabet')),
                ('dizziness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Dizziness', verbose_name='Bosh aylanishi')),
                ('hepatitis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Hepatitis', verbose_name='Gepatit B')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.User', verbose_name='Bemor')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.Pressure', verbose_name='Qon bosimi')),
            ],
            options={
                'verbose_name': 'Bemor kasalligi',
                'verbose_name_plural': 'Bemor kasalliklari',
            },
        ),
    ]
