# Generated by Django 3.2.5 on 2022-02-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20220107_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(verbose_name='Kod')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user_id', to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Bemor kodi ',
                'verbose_name_plural': 'Bemor kodlari',
            },
        ),
    ]
