# Generated by Django 3.2.5 on 2022-03-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user_id', to='patient.user', verbose_name='Bemor'),
        ),
    ]
