# Generated by Django 3.2.5 on 2022-03-07 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('illness', '0002_auto_20220107_1418'),
        ('patient', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_illness',
            name='alcohol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.alcohol', verbose_name='Spirtli ichimlik ichasizmi?'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='blood_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.blood_disease', verbose_name='Qon kasali'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='epilepsy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.epilepsy', verbose_name='Epilepsiya'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='heart_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.heart_attack', verbose_name='Yurak xurujiga uchraganmisiz?'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='medications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.medications', verbose_name='Doimiy dorilar'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='oncologic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.oncologic', verbose_name='Onkologik kasalliklar'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='pregnancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.pregnancy', verbose_name='Homiladorlik'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.stroke', verbose_name='Insultga uchraganmisiz?'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='tuberculosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.tuberculosis', verbose_name='Sil kasalligi'),
        ),
    ]
