# Generated by Django 3.2.5 on 2022-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20220307_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooth',
            name='comment',
            field=models.CharField(default=None, max_length=255, verbose_name='Izoh'),
            preserve_default=False,
        ),
    ]
