# Generated by Django 3.2.5 on 2022-03-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20220311_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_illness', to='patient.user', verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='other_illness',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_otherillness', to='patient.user', verbose_name='Bemor'),
        ),
    ]
