# Generated by Django 3.2.5 on 2022-03-28 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('illness', '0002_auto_20220107_1418'),
        ('patient', '0009_auto_20220323_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='aids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.aids', verbose_name='OITS'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='allergy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.allergy', verbose_name='Allergiya'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='anesthesia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.anesthesia', verbose_name='Narkoz'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='asthma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.asthma', verbose_name='Bronxial astma'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='diabet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.diabet', verbose_name='Qandli diabet'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='dizziness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.dizziness', verbose_name='Bosh aylanishi'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='hepatitis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.hepatitis', verbose_name='Gepatit B'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='pressure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.pressure', verbose_name='Qon bosimi'),
        ),
    ]
