# Generated by Django 3.2.5 on 2022-04-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('illness', '0003_auto_20220420_1018'),
        ('patient', '0010_auto_20220328_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_illness',
            name='blood_disease',
        ),
        migrations.AddField(
            model_name='illness',
            name='fainting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.fainting', verbose_name='Bosh aylanishi'),
        ),
        migrations.AddField(
            model_name='other_illness',
            name='breastfeeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='illness.breastfeeding', verbose_name='Emizasizmi?'),
        ),
    ]
