# Generated by Django 3.2.5 on 2022-07-19 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_illness_fainting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jami'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_payment', to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
    ]
